# Generated by Django 3.1.6 on 2021-04-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsme',
            name='Laid_off',
        ),
    ]
