# Generated by Django 3.1.6 on 2021-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_id', models.IntegerField()),
                ('Application_date', models.DateTimeField()),
                ('H_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='H_SME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_id', models.IntegerField()),
                ('Company', models.CharField(max_length=20)),
                ('Sector', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('No_of_employees', models.IntegerField()),
                ('Years', models.IntegerField()),
                ('Ready', models.CharField(max_length=10)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='L_SME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_id', models.IntegerField()),
                ('Company', models.CharField(max_length=20)),
                ('Sector', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
                ('No_of_employees', models.IntegerField()),
                ('Years', models.IntegerField()),
            ],
        ),
    ]
