# Generated by Django 3.1.6 on 2021-03-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='H_SME',
            new_name='Hsme',
        ),
        migrations.RenameModel(
            old_name='L_SME',
            new_name='Lsme',
        ),
    ]
