# Generated by Django 3.1.6 on 2021-03-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210312_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hsme',
            old_name='No_of_employees',
            new_name='No_of_employees_required',
        ),
        migrations.RenameField(
            model_name='lsme',
            old_name='No_of_employees',
            new_name='No_of_employees_being_laid_off',
        ),
    ]
